### ISSUE TITLE
dos33 doesn't exit with nonzero status on most errors

### ISSUE THREAD

**Issue by micahcowan** [deater/dos33fsprogs#13]
Example:
```
$ dos33 ROMX-BASIC.DSK BSAVE -a 8000 basic-loader.bin BLOADER; echo $?
Error!  basic-loader.bin not found!
0
```

Expected result: final line should read `1`.

Motivation: it is often convenient to use **dos33** within a Makefile, and it may be desired to remove a disk-in-progress in the event that some operation goes wrong, so that future `make` invocations don't assume that a disk image's existence means it was successfully completed. But this is only possible if **dos33** correctly indicates its success or failure to the parent process (shell).

**Comment by deater** [comment]
OK, I've made some changes that should address this, ending in cbdb595f63292cffc2af71b9b98f59fcdd8457e2

due to the confusing github interface I forgot you had submitted a series of patches too, after I had already independently done a lot of the changes.  I went through your patch and I think my changes cover all of the cases from your patch series

**Comment by micahcowan** [comment]
Oh no! Sorry you duplicated the work. And thank you for giving it your attention! I know you're a busy guy with lots of sticks in the fire ^_^

I'll make a point from now on to explicitly, verbally call out the existence of a PR to address the issue. I see that Github calls out that it was mentioned, but doesn't really make it obvious that the call-out was done from a PR.
